version: "3.7"
services:
  p:
    build: ./db
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-HSE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432

  app:
    build: .
    depends_on:
      - database
    environment:
      WAIT_HOSTS: postgres:5432
    ports:
      - 8080:8080

volumes:
  postgres: